### ISSUE TITLE
JOSS Review Checklist

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#33]
[General checks](https://joss.readthedocs.io/en/latest/review_checklist.html#general-checks)

- [x] Repository: Is the source code for this software available at the [repository url](https://github.com/DistrictDataLabs/yellowbrick)? furrer-lab/devel-abn#134 
- [x] License: Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] Contribution and authorship: Has the submitting author made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

[Functionality](https://joss.readthedocs.io/en/latest/review_checklist.html#functionality)

- [x] Installation: Does installation proceed as outlined in the documentation? furrer-lab/abn#70
- [x] Functionality: Have the functional claims of the software been confirmed?
- [x] Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

[Documentation](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation)

- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x]  tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] furrer-lab/devel-abn#138

[Software paper](https://joss.readthedocs.io/en/latest/review_checklist.html#software-paper)

- [x] Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] A statement of need: Does the paper have a section titled ‘Statement of need’ that clearly states what problems the software is designed to solve, who the target audience is, and its relation to other work?
- [x] State of the field: Do the authors describe how this software compares to other commonly-used packages?
- [x] Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] furrer-lab/devel-abn#139
