### ISSUE TITLE
JOSS Submission Checklist

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#34]
- [x] The software must be open source as per the [OSI definition](https://opensource.org/osd).
- [x] The software must be hosted at a location where users can open issues and propose code changes without manual approval of (or payment for) accounts. furrer-lab/devel-abn#134 
- [x] The software must have an obvious research application.
- [x] You must be a major contributor to the software you are submitting, and have a GitHub account to participate in the review process.
- [x] Your paper must not focus on new research results accomplished with the software.
- [x] Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

In addition, the software associated with your submission must:
- [x] Be stored in a repository that can be cloned without registration.
- [x] Be stored in a repository that is browsable online without registration.
- [x] Have an issue tracker that is readable without registration.
- [x] Permit individuals to create issues/file tickets against your repository.

In addition, JOSS requires that software should be 
- [x] feature-complete (i.e., no half-baked solutions), 
- [x] packaged appropriately according to common community standards for the programming language being used (e.g., [Python](https://packaging.python.org/), [R](https://r-pkgs.org/index.html)), furrer-lab/devel-abn#134 
- [x] and designed for maintainable extension (not one-off modifications of existing tools). “Minor utility” packages, including “thin” API clients, and single-function packages are not acceptable.

Co-publication of science, methods, and software:
- [x] We ask that authors indicate whether related publications (published, in review, or nearing submission) exist as part of submitting to JOSS.

CoI Policy:
- [x] furrer-lab/devel-abn#140
- [x] furrer-lab/devel-abn#141
- [x] Review process: Editors and reviewers must be informed of any potential conflicts of interest before reviewing the manuscript to ensure unbiased evaluation of the research.
- [x] Compliance: Authors who fail to comply with the COI policy may have their manuscript rejected or retracted if a conflict is discovered after publication.
- [x] Review and Update: This COI policy will be reviewed and updated regularly to ensure it remains relevant and effective.

[What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)
Given this format, a “full length” paper is not permitted, and software documentation such as API (Application Programming Interface) functionality should not be in the paper and instead should be outlined in the software documentation.
- [x] furrer-lab/devel-abn#142
- [x] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [x] A Statement of need section that clearly illustrates the research purpose of the software and places it in the context of related work.
- [x] A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
- [x] Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
- [x] Acknowledgement of any financial support. see furrer-lab/devel-abn#141
- [x] [Citations](https://joss.readthedocs.io/en/latest/submitting.html#citations)
Bibliographic data should be collected in a file _paper.bib_; it should be formatted in the BibLaTeX format, although plain BibTeX is acceptable as well. see furrer-lab/devel-abn#139 
   - [x] references include _full names of venues_, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.

[Checking that your paper compiles](https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles)
- [x] furrer-lab/abn#20
